'use client';

import { useEffect, useState } from 'react';
import { InsightSummary } from '@/lib/types';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { Brain, AlertTriangle, Lightbulb } from 'lucide-react';

export default function InsightsPage() {
  const [insight, setInsight] = useState<InsightSummary | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  async function generateInsights() {
    setGenerating(true);
    try {
      const res = await fetch('/api/insights', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ signals: [] }) // Will fetch internally on the backend
      });
      const data = await res.json();
      setInsight(data);
    } catch (e) {
      console.error(e);
    } finally {
      setGenerating(false);
      setLoading(false);
    }
  }

  useEffect(() => {
    generateInsights();
  }, []);

  return (
    <div className="flex flex-col gap-xl">
      <div className="flex items-center justify-between" style={{ borderBottom: '1px solid var(--color-hairline)', paddingBottom: 'var(--spacing-md)' }}>
        <div>
          <h1 className="display-lg">AI Research Report</h1>
          <p className="body-md text-muted mt-sm">Generated by Hack Club AI using recent market signals.</p>
        </div>
        <button 
          className="button-primary flex items-center gap-sm" 
          onClick={generateInsights} 
          disabled={generating}
        >
          <Brain size={18} />
          {generating ? 'Synthesizing...' : 'Regenerate Analysis'}
        </button>
      </div>

      {loading || generating ? (
        <div className="flex flex-col gap-lg items-center justify-center py-xxl text-center">
          <div className="orb-bg orb-lavender" style={{ position: 'relative', width: '120px', height: '120px', margin: '0 auto', opacity: 0.5 }}></div>
          <div className="title-md mt-md">Analyzing signals with Hack Club AI...</div>
          <p className="body-sm text-muted">This may take a moment while the model processes real-time data.</p>
        </div>
      ) : insight ? (
        <div className="flex flex-col gap-xl">
          
          <div className="grid" style={{ gridTemplateColumns: '2fr 1fr', gap: 'var(--spacing-lg)' }}>
            <Card style={{ borderTop: '4px solid var(--color-ink)' }}>
              <CardHeader>
                <CardTitle>Executive Summary</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="body-md text-body" style={{ lineHeight: 1.6 }}>{insight.summary}</p>
              </CardContent>
            </Card>

            <Card className="flex flex-col items-center justify-center text-center">
              <CardContent className="flex flex-col items-center gap-sm py-lg">
                <div className="title-sm text-muted">Sentiment Score</div>
                <div className="display-xl" style={{ 
                  color: insight.sentimentScore > 0.3 ? 'var(--color-semantic-success)' : 
                         insight.sentimentScore < -0.3 ? 'var(--color-semantic-error)' : 'var(--color-ink)' 
                }}>
                  {insight.sentimentScore > 0 ? '+' : ''}{Math.round(insight.sentimentScore * 100)}
                </div>
                <Badge variant={insight.sentimentScore > 0.3 ? 'success' : insight.sentimentScore < -0.3 ? 'error' : 'default'}>
                  {insight.sentimentScore > 0.3 ? 'Bullish' : insight.sentimentScore < -0.3 ? 'Bearish' : 'Neutral'}
                </Badge>
              </CardContent>
            </Card>
          </div>

          <div className="grid" style={{ gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 'var(--spacing-lg)' }}>
            <Card style={{ backgroundColor: 'var(--color-surface-strong)' }}>
              <CardHeader>
                <CardTitle className="flex items-center gap-sm text-body-strong">
                  <AlertTriangle size={20} style={{ color: 'var(--color-semantic-error)' }} />
                  Risk Factors
                </CardTitle>
              </CardHeader>
              <CardContent>
                {insight.riskFactors.length > 0 ? (
                  <ul className="flex flex-col gap-sm">
                    {insight.riskFactors.map((risk, i) => (
                      <li key={i} className="flex gap-sm items-start">
                        <span className="body-strong" style={{ color: 'var(--color-muted)' }}>{i + 1}.</span>
                        <span className="body-md text-body">{risk}</span>
                      </li>
                    ))}
                  </ul>
                ) : (
                  <div className="body-sm text-muted">No major risks identified in the current data stream.</div>
                )}
              </CardContent>
            </Card>

            <Card style={{ backgroundColor: 'var(--color-surface-strong)' }}>
              <CardHeader>
                <CardTitle className="flex items-center gap-sm text-body-strong">
                  <Lightbulb size={20} style={{ color: 'var(--color-semantic-success)' }} />
                  Opportunities
                </CardTitle>
              </CardHeader>
              <CardContent>
                {insight.opportunities.length > 0 ? (
                  <ul className="flex flex-col gap-sm">
                    {insight.opportunities.map((opp, i) => (
                      <li key={i} className="flex gap-sm items-start">
                        <span className="body-strong" style={{ color: 'var(--color-muted)' }}>{i + 1}.</span>
                        <span className="body-md text-body">{opp}</span>
                      </li>
                    ))}
                  </ul>
                ) : (
                  <div className="body-sm text-muted">No specific opportunities surfaced yet.</div>
                )}
              </CardContent>
            </Card>
          </div>

        </div>
      ) : (
        <div className="p-xl bg-canvas-soft text-center body-md text-muted" style={{ borderRadius: 'var(--rounded-lg)', border: '1px dashed var(--color-hairline-strong)' }}>
          Failed to load insights. Please try regenerating.
        </div>
      )}
    </div>
  );
}
